Wrote getLatestTransaction function and display that in the header section
DAVFoundation/xplore pull request #122
Opened 2018-03-24 16:04 UTC by bicep

(Based off the branch where I renamed getLatestBlock to getLatestBlockNumber in blockchain.js).

See issue #120

2018-03-25 16:35 UTC, TalAter requested changes

2018-03-25 16:35 UTC, TalAter commented on src/components/HeaderSections.jsx
> +  newMethod() {
Can this be removed?

2018-03-25 16:35 UTC, TalAter commented on src/reducers/headerSections.js
> +const deepCopyState = (state) => JSON.parse(JSON.stringify(state));
This does not seem like the proper place to define this function

2018-03-26 07:07 UTC, bicep commented
Made the changes, placed the method in utils.js. Let me know if there is a better place to put it.

Also I used the react-text-fit package to ensure the text in the headerSection fits,  but I'm not sure if this is the best package to use. I'm also not convinced it's working properly because I get this warning from text-fit in the browser console:

> 
webpack-internal:///584:140 Can not process element without height. Make sure the element is displayed and has a static height.

Please give me a better solution if you know of one.

2018-12-01 01:20 UTC, debragail commented
@TalAter ready to merge?

2018-12-07 20:09 UTC, debragail commented
Thanks @bicep!  what version of webpack is being used in the build?  Can you pull the latest build and see if you get the same error?

2018-12-08 10:30 UTC, bicep commented
Hi @debragail I'm sorry for my late reply. 

I think these were Webpack issues with react-text-fit, a package that I installed in dev dependencies to get the block id and eth value to fit nicely into the header box.

It's fixed now after I manually rebased. 

It looks very cramped though:
<img width="679" alt="screen shot 2018-12-08 at 6 28 22 pm" src="https://user-images.githubusercontent.com/11747211/49685021-3366e100-fb17-11e8-8e0e-8228e497499e.png">

Perhaps people will have thoughts about a better way.

2018-12-13 02:53 UTC, debragail commented
> Hi @debragail I'm sorry for my late reply.
> 
> I think these were Webpack issues with react-text-fit, a package that I installed in dev dependencies to get the transaction id and eth value to fit nicely into the header box.
> 
> It's fixed now after I manually rebased.
> 
> It looks very cramped though:
> <img alt="screen shot 2018-12-08 at 6 28 22 pm" width="679" src="https://user-images.githubusercontent.com/11747211/49685021-3366e100-fb17-11e8-8e0e-8228e497499e.png">
> 
> Perhaps people will have thoughts about a better way.

Try this layout.  I kept the margins the same just changed the ordering to fit the usecase.

![transimgdav_fix](https://user-images.githubusercontent.com/552529/49912495-3297bd00-fe3f-11e8-83d4-13ed47aedbbf.png)

2018-12-13 02:54 UTC, debragail commented
You could also bring the RPC image up as well so there is equal bottom padding.

2018-12-13 19:56 UTC, TalAter commented
Looks good @debragail 
Are you able to make those changes?

2018-12-14 06:46 UTC, debragail commented
@talalter I was hoping @bicep could make the change so we could resolve.  @bicep let me know if you can update this.  Really appreciate your time on this and attention to detail.

2018-12-15 08:51 UTC, bicep commented
Hello!

Trucated the id and put caps on the keys. It should be good to go now! Also managed the margins a little bit in the styles.

<img width="1369" alt="screen shot 2018-12-15 at 4 47 50 pm" src="https://user-images.githubusercontent.com/11747211/50041066-96adc180-0089-11e9-95a4-57f833976559.png">

2018-12-16 07:08 UTC, debragail commented
Thanks so much @bicep.  I just created a new issue I need @TalAter to review but the truncation might also help in mobile view for other sections.

https://github.com/DAVFoundation/xplore/issues/151

2018-12-16 08:55 UTC, merged

2018-12-16 08:56 UTC, TalAter commented
Merged!

Thanks Roger.