Created a method to return RPC server on the top block view
DAVFoundation/xplore pull request #46
Opened 2018-02-17 22:47 UTC by THEozmic

## Description
Created `getRpcServer` action, updated the `topBlocks` reducer and displayed the rpc server on the 
view

## Related Issue
https://github.com/DAVFoundation/xplore/issues/29

## Motivation and Context
Helps user see what their RPC server is

## How Has This Been Tested?
- Wrote a new test case
- Ran `npm test`
- Looked through the app and made sure everything still works as expected

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/15184445/36139726-fdb06fda-109e-11e8-9238-1c42cd5aaa3b.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-02-19 16:47 UTC, griffobeid requested changes
Overall, excellent pull request @THEozmic! I just have a few suggestions for you to make it even better.

2018-02-19 16:47 UTC, griffobeid commented on test/specs/reducers/transactions.spec.js
> +          blockNumber: '3' }],
The changes here are irrelevant to the issue and should be made in a separate pull request.

2018-02-19 16:47 UTC, griffobeid commented on test/specs/reducers/topBlocks.spec.js
> +  describe('When GET_RPC_SERVER action is fired', () => {
Your description here should be consistent with what you end up naming the action.

2018-02-19 16:47 UTC, griffobeid commented on src/containers/TopBlocksContainer.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(TopBlocks);
Correct me if I'm wrong here @TalAter, but I believe the changes to this file are unnecessary. You are making a call to `getRpcServer()` inside of the `topBlocks` reducer.

2018-02-19 16:47 UTC, griffobeid commented on src/components/TopBlocks.jsx
> +  getRpcServer: PropTypes.func
What is the purpose line 52 here? The RPC server should already be fed by the `blockList` prop.

2018-02-19 16:47 UTC, griffobeid commented on src/actions/index.js
> +export const getRpcServer = createAction('GET_TOP_BLOCKS', getRpcServerCall);
I feel as though 'GET_TOP_BLOCKS' is not the most appropriate name for this action. Maybe go with 'GET_RPC_SERVER' instead.

2018-02-19 17:50 UTC, THEozmic commented
Hey @griffobeid, I expected to get a few these comments because I wasn't very sure about how and where to place things. Thanks for the feedback, I'll make the changes as soon as is possible.

2018-02-21 11:24 UTC, THEozmic commented
@griffobeid I've made some changes, please review and let me know if anything else isn't right.

2018-02-21 13:53 UTC, griffobeid commented
Awesome, @THEozmic 💪 thanks for another great pull request! 😄

2018-02-21 13:53 UTC, merged